
services:
  frontend:
    build: ./frontend
    container_name: pis-frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: pis-backend
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-postgres:5432/mydb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATA_MONGODB_URI=mongodb://root:rootpassword@mongo:27017/mikrodb?authSource=admin
    depends_on:
      - db-postgres
      - db-mongo
    networks:
      - app-network

  db-postgres:
    image: postgres:15
    container_name: db-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5434:5432"
    volumes:
      - ./db-postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  db-mongo:
    image: mongo:8
    container_name: db-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: mikrodb
    volumes:
      - ./mongo-data:/data/db
      - ./db-mongo:/docker-entrypoint-initdb.d
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
